site_name: CompSci Notes
site_author: Frank Zhang
theme:
    name: material
markdown_extensions:
    - toc:
          permalink: True
    - admonition
    - smarty
    - attr_list
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - js/mathjax.min.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
