site_name: CompSci Notes
site_author: Frank Zhang
theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          accent: teal
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: teal
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
markdown_extensions:
    - toc:
          permalink: True
    - admonition
    - smarty
    - attr_list
    - pymdownx.details
    - md_in_html
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex:
          generic: true
plugins:
    - glightbox
extra_javascript:
    - js/mathjax.min.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
